[HDMI-A-1]
path = "/home/ekoehler/Pictures/walls/whiteFlower219.jpg"

[eDP-1]
path = "/home/ekoehler/Pictures/walls/whiteFlower169.jpeg"

[DP-1]
path = "/home/ekoehler/Pictures/walls/whiteFlower169.jpeg"
